name: Cypress
on: [push, pull_request]
jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm ci
      - run: npm run cypress:run
      - name: Start Server
        run: npm run dev & # Запускаем сервер в фоновом режиме (&)
      - name: Wait for Server
        run: |
          # Ждем, пока сервер станет доступен
          npx wait-on http://localhost:3000 -t 60000 # Ждем до 60 секунд
      - name: Run Cypress tests
        run: npm run cypress:run
